/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import static forms.panelGestion.listaProdu;
import java.util.Set;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.Producto;

/**
 *
 * @author PC1
 */
public class consulPrecio extends javax.swing.JPanel {
    
    DefaultTableModel modeloTableNombre;
    TableRowSorter<DefaultTableModel> sortInput;
    
    private void llenarTableNombre(Long precioMin, Long precioMax) {
        tableNombre.setShowGrid(false);
        modeloTableNombre = (DefaultTableModel) tableNombre.getModel();
        modeloTableNombre.setRowCount(0);
        for (Producto p : listaProdu) {
            if (p.getPrecio() >= precioMin && p.getPrecio() <= precioMax) {
                modeloTableNombre.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getRubro(),
                    p.getStock()
                });
            }
        }
    }
    
    

    private void filtrarPrecio() {
        Long precioMin = Long.MIN_VALUE;
        Long precioMax = Long.MAX_VALUE;
        try {
            if (!textPrecioMin.getText().trim().isEmpty()) {
                precioMin = Long.valueOf(textPrecioMin.getText().trim());
            }
            
            if (!textPrecioMax.getText().trim().isEmpty()) {
                precioMax = Long.valueOf(textPrecioMax.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato no valido para campo numerico.");      
        return;
    }
        
        llenarTableNombre(precioMin, precioMax);
    
}

public consulPrecio() {
        initComponents();
        tableNombre.setShowGrid(false);
        llenarTableNombre(Long.MIN_VALUE, Long.MIN_VALUE);
        textPrecioMin.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate (DocumentEvent e) {filtrarPrecio(); }
            public void changedUpdate (DocumentEvent e) {filtrarPrecio(); }
            public void removeUpdate (DocumentEvent e) {filtrarPrecio(); }      
        });
        
        textPrecioMax.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate (DocumentEvent e) {filtrarPrecio();}
            public void changedUpdate (DocumentEvent e) {filtrarPrecio();}
            public void removeUpdate (DocumentEvent e) {filtrarPrecio(); }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textPrecioMin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNombre = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textPrecioMax = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTAR POR PRECIO");

        jLabel2.setText("Precio entre: $");

        textPrecioMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioMinActionPerformed(evt);
            }
        });

        tableNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Rubro", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tableNombre);

        jLabel3.setText("y: $");

        textPrecioMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textPrecioMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioMinActionPerformed

    private void textPrecioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioMaxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNombre;
    private javax.swing.JTextField textPrecioMax;
    private javax.swing.JTextField textPrecioMin;
    // End of variables declaration//GEN-END:variables
}
