/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;
import logica.Producto;
import static forms.panelGestion.listaProdu;
import javax.swing.JOptionPane;

/**
 *
 * @author PC1
 */
public class consulRubro extends javax.swing.JPanel {
    
    DefaultTableModel modeloTableProd1;
    

    private void llenarTablaProd1() {
        modeloTableProd1 = (DefaultTableModel) tableNombre.getModel();
        modeloTableProd1.setRowCount(0);
        for (Producto p : listaProdu) {
            modeloTableProd1.addRow(new Object[]{
                p.getCodigo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getRubro(),
                p.getStock()
            });
        }
    }

    private void filtrarPorRubro(String categoria) {
        modeloTableProd1.setRowCount(0);
        for (Producto p : listaProdu) {
            if (p.getRubro().equals(categoria)) {
                modeloTableProd1.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getRubro(),
                    p.getStock()
                });
            }
        }
    }
    public consulRubro() {
        initComponents();
        tableNombre.setShowGrid(false);
        llenarTablaProd1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNombre = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboRubro1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(744, 518));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTAR POR RUBRO");

        tableNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Rubro", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tableNombre);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Filtrar por Rubro");

        comboRubro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Bebidas", "Alimentos", "Perfumeria", "Higiene", "Limpieza", "Otros", " " }));
        comboRubro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRubro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(162, 162, 162)
                        .addComponent(comboRubro1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRubro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboRubro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRubro1ActionPerformed
        try {
            String categoria = (String) comboRubro1.getSelectedItem();
            if (comboRubro1.getSelectedItem().equals("Seleccionar...")) {
                llenarTablaProd1();
            } else {
                filtrarPorRubro(categoria);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay elementos para mostrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comboRubro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboRubro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNombre;
    // End of variables declaration//GEN-END:variables
}
