/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.awt.*;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Producto;

/**
 *
 * @author PC1
 */
public class panelGestion extends javax.swing.JPanel {

    public static TreeSet<Producto> listaProdu = new TreeSet<>();
    DefaultTableModel modeloTableProd1;
    

    private void llenarTablaProd1() {
        modeloTableProd1 = (DefaultTableModel) tableProdu.getModel();
        modeloTableProd1.setRowCount(0);
        for (Producto p : listaProdu) {
            modeloTableProd1.addRow(new Object[]{
                p.getCodigo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getRubro(),
                p.getStock()
            });
        }
    }

    private void filtrarPorRubro(String categoria) {
        modeloTableProd1.setRowCount(0);
        for (Producto p : listaProdu) {
            if (p.getRubro().equals(categoria)) {
                modeloTableProd1.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getRubro(),
                    p.getStock()
                });
            }
        }
    }

    private void habilitarCampos(boolean habilitar) {
        textCod.setEnabled(habilitar);
        textDesc.setEnabled(habilitar);
        textPrecio.setEnabled(habilitar);
        comboRubro2.setEnabled(habilitar);
        spinnerStock.setEnabled(habilitar);
    }

    private void habilitarBotones(boolean nuevo, boolean guardar, boolean actualizar, boolean borrar, boolean buscar) {
        buttonNuevo.setEnabled(nuevo);
        buttonGuardar.setEnabled(guardar);
        buttonAct.setEnabled(actualizar);
        buttonBorrar.setEnabled(borrar);
        buttonBuscar.setEnabled(buscar);
    }

    private void limpiarTodo() {
        textCod.setText("");
        textDesc.setText("");
        textPrecio.setText("");
        comboRubro2.setSelectedIndex(0);
        spinnerStock.setValue(1);
    }

    private void llenarTextField(Producto produ) {
        textCod.setText(String.valueOf(produ.getCodigo()));
        textDesc.setText(produ.getDescripcion());
        textPrecio.setText(String.valueOf(produ.getPrecio()));
        comboRubro2.setSelectedItem(produ.getRubro());
        spinnerStock.setValue(produ.getStock());
    }

    private Producto buscarPorCodigo(Long cod) {
        for (Producto p : listaProdu) {
            if (p.getCodigo().equals(cod)) {
                return p;
            }
        }
        return null;
    }

    private void buscarProductoTable(Long cod) {
        modeloTableProd1.setRowCount(0);
        for (Producto p : listaProdu) {
            if (p.getCodigo().equals(cod)) {
                modeloTableProd1.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getRubro(),
                    p.getStock()
                });
                return;
            }

        }
        JOptionPane.showMessageDialog(this, "No se encontro el producto.");
        llenarTablaProd1();
    }

    /**
     * Creates new form panelGestion
     */
    public panelGestion() {
        initComponents();
        tableProdu.setShowGrid(false);
        buttonNuevo.setToolTipText("Limpia los campos para añadir un producto nuevo.");
        buttonGuardar.setToolTipText("Guarda el producto en la lista.");
        buttonAct.setToolTipText("Luego de realizar cambios, actualiza el producto.");
        buttonBorrar.setToolTipText("Elimina el producto de la lista.");
        buttonBuscar.setToolTipText("Busca por codigo de producto");

        habilitarCampos(false);
        habilitarBotones(true, false, false, false, false);
        tableProdu.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                textCod.setEditable(false);
                if (tableProdu.getSelectedRow() == -1) {
                    return;
                }
                Long cod = (Long) tableProdu.getValueAt(tableProdu.getSelectedRow(), 0);
                Producto produ = buscarPorCodigo(cod);
                if (produ != null) {
                    llenarTextField(produ);
                    habilitarBotones(true, false, true, true, true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboRubro1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        comboRubro2 = new javax.swing.JComboBox<>();
        spinnerStock = new javax.swing.JSpinner();
        textDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        textPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textCod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonBorrar = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonAct = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jRadioButton1.setText("jRadioButton1");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE PRODUCTOS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Filtrar por Rubro");

        comboRubro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Bebidas", "Alimentos", "Perfumeria", "Higiene", "Limpieza", "Otros" }));
        comboRubro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRubro1ActionPerformed(evt);
            }
        });

        tableProdu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Rubro", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tableProdu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(comboRubro1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(277, 277, 277))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRubro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        comboRubro2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Bebidas", "Alimentos", "Perfumeria", "Higiene", "Limpieza", "Otros", " " }));
        comboRubro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRubro2ActionPerformed(evt);
            }
        });

        spinnerStock.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Descripcion");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Precio");

        buttonBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-search-25.png")); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-cancel-25.png")); // NOI18N
        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Stock");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Rubro");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textCod)
                    .addComponent(textDesc)
                    .addComponent(textPrecio)
                    .addComponent(comboRubro2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboRubro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinnerStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSalir))
                .addContainerGap())
        );

        buttonBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-delete-50.png")); // NOI18N
        buttonBorrar.setText("Eliminar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-plus-50.png")); // NOI18N
        buttonNuevo.setText("Nuevo");
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-done-50.png")); // NOI18N
        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonAct.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC1\\Desktop\\Facu\\LabProg\\TP6_GUI_PRODUCTO\\tp6-ejercicio2\\src\\imagenes\\icons8-refresh-50.png")); // NOI18N
        buttonAct.setText("Actualizar");
        buttonAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonNuevo)
                .addGap(50, 50, 50)
                .addComponent(buttonGuardar)
                .addGap(54, 54, 54)
                .addComponent(buttonAct)
                .addGap(54, 54, 54)
                .addComponent(buttonBorrar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuevo)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonAct)
                    .addComponent(buttonBorrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        habilitarCampos(true);
        habilitarBotones(true, true, true, true, true);
        limpiarTodo();
        llenarTablaProd1();
        textCod.setEditable(true);
        tableProdu.clearSelection();
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        if (textCod.getText().isEmpty() || textDesc.getText().isEmpty() || textPrecio.getText().isEmpty() || comboRubro2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sCod = textCod.getText();
        String desc = textDesc.getText();
        String sPrecio = textPrecio.getText();
        String rubro = (String) comboRubro2.getSelectedItem();
        int stock = (int) spinnerStock.getValue();

        Long cod;
        Double precio;

        try {
            cod = Long.valueOf(sCod);
            precio = Double.valueOf(sPrecio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato no valido para campo numerico", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (Producto p : listaProdu) {
            if (p.getCodigo().equals(cod)) {
                JOptionPane.showMessageDialog(this, "Ya existe un producto con el codigo ingresado", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        int confirmarCarga = JOptionPane.showOptionDialog(this, "Desea cargar este producto?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");

        if (confirmarCarga == 0) {
            Producto produ = new Producto(cod, desc, rubro, precio, stock);
            listaProdu.add(produ);
            llenarTablaProd1();
            habilitarBotones(true, false, false, false, false);
        }

    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActActionPerformed
        String sCod = textCod.getText();
        String desc = textDesc.getText();
        String sPrecio = textPrecio.getText();
        String rubro = (String) comboRubro2.getSelectedItem();
        int stock = (int) spinnerStock.getValue();

        Long cod;
        Double precio;

        if (tableProdu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Ningun producto seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            cod = Long.valueOf(sCod);
            precio = Double.valueOf(sPrecio);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato no valido para campo numerico", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Producto produ = buscarPorCodigo(cod);
        if (produ != null) {
            produ.setDescripcion(desc);
            produ.setPrecio(precio);
            produ.setRubro(rubro);
            produ.setStock(stock);

            llenarTablaProd1();

            JOptionPane.showMessageDialog(this, "El producto fue actualizado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonActActionPerformed

    private void comboRubro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRubro1ActionPerformed
        try {
            String categoria = (String) comboRubro1.getSelectedItem();
            if (comboRubro1.getSelectedItem().equals("Seleccionar...")) {
                llenarTablaProd1();
            } else {
                filtrarPorRubro(categoria);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay elementos para mostrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comboRubro1ActionPerformed

    private void comboRubro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRubro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRubro2ActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        if (tableProdu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
            return;
        }

        JOptionPane.showOptionDialog(this, "Esta seguro de eliminar este producto?", "Confirmar", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE, null, new Object[]{"Si"}, "Si");

        Long cod = (Long) tableProdu.getValueAt(tableProdu.getSelectedRow(), 0);
        Producto produ = buscarPorCodigo(cod);
        listaProdu.remove(produ);
        modeloTableProd1.removeRow(tableProdu.getSelectedRow());
        modeloTableProd1 = (DefaultTableModel) tableProdu.getModel();
        llenarTextField(produ);
        habilitarBotones(true, true, true, true, true);
        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
        limpiarTodo();
        textCod.setEditable(true);
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        String sCod = textCod.getText();

        if (sCod == null || sCod.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un codigo para buscar un producto.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Long cod;
            try {
                cod = Long.valueOf(sCod);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Formato no valido para campo numerico", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            buscarProductoTable(cod);
            tableProdu.setRowSelectionInterval(0, 0);

        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        java.awt.Container panelContainer = this.getParent();
        panelContainer.setVisible(false);
    }//GEN-LAST:event_buttonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAct;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JComboBox<String> comboRubro1;
    private javax.swing.JComboBox<String> comboRubro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JSpinner spinnerStock;
    private javax.swing.JTable tableProdu;
    private javax.swing.JTextField textCod;
    private javax.swing.JTextField textDesc;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
