/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import forms.panelGestion;
import java.awt.*;
import javax.swing.UIManager;

/**
 *
 * @author PC1
 */
public class superMerka2 extends javax.swing.JFrame {

    /**
     * Creates new form superMerka2
     */
    public superMerka2() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setSize(800, 600);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuAdm = new javax.swing.JMenu();
        menuGestion = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuNombre = new javax.swing.JMenuItem();
        menuPrecio = new javax.swing.JMenuItem();
        menuRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperMerka2");
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelContainer.setLayout(new java.awt.CardLayout());

        menuAdm.setText("Administracion");
        menuAdm.setToolTipText("");
        menuAdm.setName(""); // NOI18N

        menuGestion.setText("Gestion de Productos");
        menuGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionActionPerformed(evt);
            }
        });
        menuAdm.add(menuGestion);

        menuBar.add(menuAdm);

        menuConsultas.setText("Consultas");

        menuNombre.setText("Consultar por Nombre");
        menuNombre.setToolTipText("");
        menuNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNombreActionPerformed(evt);
            }
        });
        menuConsultas.add(menuNombre);

        menuPrecio.setText("Consultar por Precio");
        menuPrecio.setToolTipText("");
        menuPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrecioActionPerformed(evt);
            }
        });
        menuConsultas.add(menuPrecio);

        menuRubro.setText("Consultar por Rubro");
        menuRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRubroActionPerformed(evt);
            }
        });
        menuConsultas.add(menuRubro);

        menuBar.add(menuConsultas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionActionPerformed

        panelGestion panelGestionProdu = new panelGestion();
        panelContainer.add(panelGestionProdu, "GESTION");
        CardLayout cl = (CardLayout) (panelContainer.getLayout());
        panelContainer.setVisible(true);
        cl.show(panelContainer, "GESTION");
    }//GEN-LAST:event_menuGestionActionPerformed

    private void menuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNombreActionPerformed
        
        consulNombre panelConsulNombre = new consulNombre();
        panelContainer.add(panelConsulNombre, "CONSULTA NOMBRE");
        CardLayout cl = (CardLayout) (panelContainer.getLayout());
        panelContainer.setVisible(true);
        cl.show(panelContainer, "CONSULTA NOMBRE");
        
    }//GEN-LAST:event_menuNombreActionPerformed

    private void menuPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrecioActionPerformed
        consulPrecio panelConsulPrecio = new consulPrecio();
        panelContainer.add(panelConsulPrecio, "CONSULTA PRECIO");
        CardLayout cl = (CardLayout) (panelContainer.getLayout());
        panelContainer.setVisible(true);
        cl.show(panelContainer, "CONSULTA PRECIO");
    }//GEN-LAST:event_menuPrecioActionPerformed

    private void menuRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRubroActionPerformed
        consulRubro panelConsulRubro = new consulRubro();
        panelContainer.add(panelConsulRubro, "CONSULTA RUBRO");
        CardLayout cl = (CardLayout) (panelContainer.getLayout());
        panelContainer.setVisible(true);
        cl.show(panelContainer, "CONSULTA RUBRO");
    }//GEN-LAST:event_menuRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superMerka2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superMerka2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superMerka2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superMerka2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superMerka2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAdm;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuGestion;
    private javax.swing.JMenuItem menuNombre;
    private javax.swing.JMenuItem menuPrecio;
    private javax.swing.JMenuItem menuRubro;
    private javax.swing.JPanel panelContainer;
    // End of variables declaration//GEN-END:variables
}
