/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CRN
 */
public class supermercado extends javax.swing.JFrame {

    /**
     * Creates new form supermercado
     */
    public supermercado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        productoText = new javax.swing.JMenuItem();
        jmenu2Text = new javax.swing.JMenu();
        consultaNombre = new javax.swing.JCheckBoxMenuItem();
        consultaPrecio = new javax.swing.JCheckBoxMenuItem();
        consultaRubro = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        jMenu2.setText("Administracion");

        productoText.setText("Productos");
        productoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoTextActionPerformed(evt);
            }
        });
        jMenu2.add(productoText);

        jMenuBar1.add(jMenu2);

        jmenu2Text.setText("Consultas");

        consultaNombre.setSelected(true);
        consultaNombre.setText("Consulta Por Nombre");
        consultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaNombreActionPerformed(evt);
            }
        });
        jmenu2Text.add(consultaNombre);

        consultaPrecio.setSelected(true);
        consultaPrecio.setText("Consulta Por Precio");
        consultaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPrecioActionPerformed(evt);
            }
        });
        jmenu2Text.add(consultaPrecio);

        consultaRubro.setSelected(true);
        consultaRubro.setText("Consulta Por Rubro");
        consultaRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaRubroActionPerformed(evt);
            }
        });
        jmenu2Text.add(consultaRubro);

        jMenuBar1.add(jmenu2Text);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoTextActionPerformed
        // TODO add your handling code here:
        
        frmProducto producto = new frmProducto();
       
       producto.setVisible(true);
       escritorio.add(producto);
       
        
        
        
        
        /*
         formularioAlumno alumno=new formularioAlumno();
       alumno.setVisible(true);
       escritorio.add(alumno);
       escritorio.moveToFront(alumno);
        */
        
        
        
        
    }//GEN-LAST:event_productoTextActionPerformed

    private void consultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaNombreActionPerformed
        // TODO add your handling code here:
       consultaNombre.setEnabled(false);
        if (consultaNombre.isSelected() ) {
        frmNombre nombre = new frmNombre();
        escritorio.add(nombre);
        nombre.setVisible(true);
   
        
        }
        consultaNombre.setEnabled(true);
    }//GEN-LAST:event_consultaNombreActionPerformed

    private void consultaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPrecioActionPerformed
        // TODO add your handling code here:
        
        
        consultaPrecio.setEnabled(false);
        if (consultaPrecio.isSelected() ) {
        frmPrecio precio = new frmPrecio();
        escritorio.add(precio);
        precio.setVisible(true);
   
        
        }
        consultaPrecio.setEnabled(true);
        
        
    }//GEN-LAST:event_consultaPrecioActionPerformed

    private void consultaRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaRubroActionPerformed
        // TODO add your handling code here:
        
        
          consultaRubro.setEnabled(false);
        if (consultaRubro.isSelected() ) {
        frmRubro rubro = new frmRubro();
        escritorio.add(rubro);
        rubro.setVisible(true);
   
        
        }
        consultaRubro.setEnabled(true);
        
        
    }//GEN-LAST:event_consultaRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem consultaNombre;
    private javax.swing.JCheckBoxMenuItem consultaPrecio;
    private javax.swing.JCheckBoxMenuItem consultaRubro;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmenu2Text;
    private javax.swing.JMenuItem productoText;
    // End of variables declaration//GEN-END:variables
}
